version: '2'
services:

    #  The Application
    app:
      image: virajkaulkar/musicapp
      volumes:
        - /var/www/storage
      env_file: '.env.prod'
      environment:
        - "DB_HOST=database"
        - "REDIS_HOST=cache"

    # The Web Server
    web:
      image: virajkaulkar/musicweb_cpy
      volumes:
         - "${LE_DIR}:/etc/letsencrypt"
      ports:
        - 80:80
        - 443:443

    # The Database
    database:
      image: mysql:5.6
      volumes:
        - dbdata:/var/lib/mysql
      environment:
        - "MYSQL_ROOT_PASSWORD=12345678"
        - "MYSQL_DATABASE=music_lab_cpy"
        - "MYSQL_USER=root"



    # redis
    cache:
      image: redis:3.0-alpine

volumes:
  dbdata:
